# -*- coding: utf-8 -*-
"""Resume_screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kfcj7lwPmvyqwaTIKFrOAXjYYfbpQ7rL
"""

!mkdir data

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(os.path.join('data','DataSet.csv'))



df['Category'].value_counts()

plt.figure()
sns.countplot(df['Category'])
plt.xticks(rotation=90)
plt.show()

df['Category'].unique()

counts=df['Category'].value_counts()
labels=df['Category'].unique()
plt.figure(figsize=(15,10))

plt.pie(counts,labels=labels,autopct='%1.1f%%',shadow=True, colors=plt.cm.coolwarm(np.linspace(0,1,3)))
plt.show()

df

df['Resume']

df['Resume'][0]

#text preprocessing

import re

def cleanResume(txt):
  # removing website links
  cleanTxt=re.sub('http\S+\s',' ',txt)
  #removing hashtags
  cleanTxt=re.sub('#\S+',' ',cleanTxt)
  #removing @
  cleanTxt=re.sub('@\S+',' ',cleanTxt)
  #removing punctuations
  cleanTxt=re.sub('[\W]+',' ',cleanTxt)
  cleanTxt=re.sub('\s+',' ',cleanTxt)
  cleanTxt=re.sub('[%s]'% re.escape("""!"#$%+-=><;:\/?()"""),' ',cleanTxt)




  return cleanTxt

cleanResume("my website ##happiness (j) like is http://hellowrold and access it khushi@gmail.com")

df['Resume']=df['Resume'].apply(lambda x:cleanResume(x))

from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()

lc.fit(df['Category'])
df['Category']=lc.transform(df['Category'])

df.Category.unique()

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english')
tfidf.fit(df['Resume'])

requiredtext=tfidf.transform(df['Resume'])

df

requiredtext

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(requiredtext,df['Category'],test_size=0.2,random_state=42)

x_train.shape

x_test.shape

from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import accuracy_score

knn = OneVsRestClassifier(KNeighborsClassifier())
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print(accuracy_score(y_test, y_pred))

import pickle
# pickle.dump(knn,open('model.pkl','wb'))
pickle.dump(tfidf,open('tfidf.pkl','wb'))

pickle.dump(knn,open('knn.pkl','wb'))

# clf=pickle.load(open('model.pkl','rb'))
# tfidf=pickle.load(open('tfidf.pkl','rb'))

myresume = """I am a data scientist specializing in machine
learning, deep learning, and computer vision. With
a strong background in mathematics, statistics,
and programming, I am passionate about
uncovering hidden patterns and insights in data.
I have extensive experience in developing
predictive models, implementing deep learning
algorithms, and designing computer vision
systems. My technical skills include proficiency in
Python, Sklearn, TensorFlow, and PyTorch.
What sets me apart is my ability to effectively
communicate complex concepts to diverse
audiences. I excel in translating technical insights
into actionable recommendations that drive
informed decision-making.
If you're looking for a dedicated and versatile data
scientist to collaborate on impactful projects, I am
eager to contribute my expertise. Let's harness the
power of data together to unlock new possibilities
and shape a better future.
Contact & Sources
Email: 611noorsaeed@gmail.com
Phone: 03442826192
Github: https://github.com/611noorsaeed
Linkdin: https://www.linkedin.com/in/noor-saeed654a23263/
Blogs: https://medium.com/@611noorsaeed
Youtube: Artificial Intelligence
ABOUT ME
WORK EXPERIENCE
SKILLES
NOOR SAEED
LANGUAGES
English
Urdu
Hindi
I am a versatile data scientist with expertise in a wide
range of projects, including machine learning,
recommendation systems, deep learning, and computer
vision. Throughout my career, I have successfully
developed and deployed various machine learning models
to solve complex problems and drive data-driven
decision-making
Machine Learnine
Deep Learning
Computer Vision
Recommendation Systems
Data Visualization
Programming Languages (Python, SQL)
Data Preprocessing and Feature Engineering
Model Evaluation and Deployment
Statistical Analysis
Communication and Collaboration
"""

cleaned_resume=cleanResume(myresume)

input_features=tfidf.transform([cleaned_resume])

prediction_id=knn.predict(input_features)[0]

category_mapping = {
    15: "Java Developer",
    23: "Testing",
    8: "DevOps Engineer",
    20: "Python Developer",
    24: "Web Designing",
    12: "HR",
    13: "Hadoop",
    3: "Blockchain",
    10: "ETL Developer",
    18: "Operations Manager",
    6: "Data Science",
    22: "Sales",
    16: "Mechanical Engineer",
    1: "Arts",
    7: "Database",
    11: "Electrical Engineering",
    14: "Health and fitness",
    19: "PMO",
    4: "Business Analyst",
    9: "DotNet Developer",
    2: "Automation Testing",
    17: "Network Security Engineer",
    21: "SAP Developer",
    5: "Civil Engineer",
    0: "Advocate",
}

category_name = category_mapping.get(prediction_id, "Unknown")

print("Predicted Category:", category_name)
print(prediction_id)

pickle.dump(knn,open('model.pkl','wb'))

